include:
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /templates.gitlab-ci.yaml
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /jobs/format.gitlab-ci.yaml

test:
  stage: test
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.6", "1"]
  extends:
    - .julia.setup
    - .julia.test
